language: go
go_import_path: hawx.me/code/xesende

env:
- GIMME_OS=linux GIMME_ARCH=amd64
- GIMME_OS=windows GIMME_ARCH=amd64

install:
- go get -d -v ./...

script: 
- go build -v ./cmd/xesende

notifications:
  email: false
